{% set version = "6.7.2" %}
{% set version_major_minor_match = '.'.join(version.split('.')[0:3]) %}

package:
  name: pyside6
  version: {{ version }}

source:
  url: https://download.qt.io/official_releases/QtForPython/pyside6/PySide6-{{ version }}-src/pyside-setup-everywhere-src-{{ version }}.tar.xz
  sha256: 3a2b0d0d6e78c9aa5ddc7f06ca4b6f11a3fe14560baeb148eea53b5d98e368c7
  patches:
    # https://bugreports.qt.io/browse/PYSIDE-1193
    - patches/pyi_osx.patch
    - patches/qfp_osx.patch

    # https://bugreports.qt.io/browse/PYSIDE-2057
    - patches/do_not_store_build_time_compiler.patch

    # change tools module location
    - patches/tools.patch

    # https://bugreports.qt.io/browse/PYSIDE-2192
    # backport of PyOS_InputHook downloaded from https://codereview.qt-project.org/c/pyside/pyside-setup/+/454254
    # should be removed for 6.7.3+
    - patches/1864c79.diff

build:
  number: 0
  skip: true  # [py<39 or not osx]
  entry_points:
    - pyside6-rcc = PySide6.scripts.pyside_tool:rcc
    - pyside6-uic = PySide6.scripts.pyside_tool:uic

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('alsa-lib-devel') }}             # [linux]
    - {{ cdt('cups-devel') }}                 # [linux]
    - {{ cdt('expat-devel') }}                # [linux and not aarch64]
    - {{ cdt('gtk2-devel') }}                 # [linux]
    - {{ cdt('gtkmm24-devel') }}              # [linux]
    - {{ cdt('libdrm-devel') }}               # [linux]
    - {{ cdt('libglvnd-glx') }}               # [linux and not x86_64]
    - {{ cdt('libglvnd-egl') }}               # [linux and not x86_64]
    - {{ cdt('libice-devel') }}               # [linux]
    - {{ cdt('libselinux-devel') }}           # [linux]
    - {{ cdt('libsm-devel') }}                # [linux]
    - {{ cdt('libx11-devel') }}               # [linux]
    - {{ cdt('libxau-devel') }}               # [linux]
    - {{ cdt('libxcb') }}                     # [linux]
    - {{ cdt('libxext-devel') }}              # [linux]
    - {{ cdt('libxfixes-devel') }}            # [linux]
    - {{ cdt('libxkbfile-devel') }}           # [linux]
    - {{ cdt('libxrender-devel') }}           # [linux]
    - {{ cdt('libxscrnsaver-devel') }}        # [linux]
    - {{ cdt('libxxf86vm-devel') }}           # [linux]
    - {{ cdt('mesa-libgl-devel') }}           # [linux]
    - {{ cdt('mesa-libgbm') }}                # [linux]
    - {{ cdt('mesa-libegl-devel') }}          # [linux]
    - {{ cdt('mesa-dri-drivers') }}           # [linux]
    - {{ cdt('xcb-util-devel') }}             # [linux]
    - {{ cdt('xcb-util-image-devel') }}       # [linux]
    - {{ cdt('xcb-util-keysyms-devel') }}     # [linux]
    - {{ cdt('xcb-util-renderutil-devel') }}  # [linux]
    - {{ cdt('xcb-util-wm-devel') }}          # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}       # [linux]
    - {{ cdt('pciutils-devel') }}             # [linux]
    - {{ cdt('libxcomposite-devel') }}        # [linux]
    - {{ cdt('libxcursor-devel') }}           # [linux]
    - {{ cdt('libxdamage-devel') }}           # [linux]
    - {{ cdt('libxrandr-devel') }}            # [linux]
    - {{ cdt('libxi-devel') }}                # [linux]
    - {{ cdt('libxshmfence-devel') }}         # [linux]
    - {{ cdt('libxtst-devel') }}              # [linux]

  host:
    - python
    - setuptools
    - libxslt
    - libxml2
    - qtbase {{ version }}
    - qtsvg {{ version }}
    - qtshadertools {{ version }}
    - qtdeclarative {{ version }}
    - qtimageformats {{ version }}
    - qttools {{ version }}
    - qttranslations {{ version }}
    - qt5compat {{ version }}
    - qtwebsockets {{ version }}
    - qtwebchannel {{ version }}
    - qtwebengine {{ version }}
    - llvmdev
    - clangdev >=9
    - libclang
    - llvmdev  {{ cxx_compiler_version }}  # [osx]
    - clangdev {{ cxx_compiler_version }}  # [osx]
  run:
    - python

test:
  requires:
    - {{ cdt('alsa-lib-devel') }}             # [linux]
    - {{ cdt('cups-devel') }}                 # [linux]
    - {{ cdt('expat-devel') }}                # [linux and not aarch64]
    - {{ cdt('gtk2-devel') }}                 # [linux]
    - {{ cdt('gtkmm24-devel') }}              # [linux]
    - {{ cdt('libdrm-devel') }}               # [linux]
    - {{ cdt('libglvnd-glx') }}               # [linux and not x86_64]
    - {{ cdt('libglvnd-egl') }}               # [linux and not x86_64]
    - {{ cdt('libice-devel') }}               # [linux]
    - {{ cdt('libselinux-devel') }}           # [linux]
    - {{ cdt('libsm-devel') }}                # [linux]
    - {{ cdt('libx11-devel') }}               # [linux]
    - {{ cdt('libxau-devel') }}               # [linux]
    - {{ cdt('libxcb') }}                     # [linux]
    - {{ cdt('libxext-devel') }}              # [linux]
    - {{ cdt('libxfixes-devel') }}            # [linux]
    - {{ cdt('libxkbfile-devel') }}           # [linux]
    - {{ cdt('libxrender-devel') }}           # [linux]
    - {{ cdt('libxscrnsaver-devel') }}        # [linux]
    - {{ cdt('libxxf86vm-devel') }}           # [linux]
    - {{ cdt('mesa-libgl-devel') }}           # [linux]
    - {{ cdt('mesa-libgbm') }}                # [linux]
    - {{ cdt('mesa-libegl-devel') }}          # [linux]
    - {{ cdt('mesa-dri-drivers') }}           # [linux]
    - {{ cdt('xcb-util-devel') }}             # [linux]
    - {{ cdt('xcb-util-image-devel') }}       # [linux]
    - {{ cdt('xcb-util-keysyms-devel') }}     # [linux]
    - {{ cdt('xcb-util-renderutil-devel') }}  # [linux]
    - {{ cdt('xcb-util-wm-devel') }}          # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}       # [linux]
    - {{ cdt('pciutils-devel') }}             # [linux]
    - {{ cdt('libxcomposite-devel') }}        # [linux]
    - {{ cdt('libxcursor-devel') }}           # [linux]
    - {{ cdt('libxdamage-devel') }}           # [linux]
    - {{ cdt('libxrandr-devel') }}            # [linux]
    - {{ cdt('libxi-devel') }}                # [linux]
    - {{ cdt('libxshmfence-devel') }}         # [linux]
    - {{ cdt('libxtst-devel') }}              # [linux]
  imports:
    - PySide6.QtConcurrent
    - PySide6.QtCore
    - PySide6.QtDesigner
    - PySide6.QtGui
    - PySide6.QtHelp
    - PySide6.QtNetwork
    - PySide6.QtOpenGL
    - PySide6.QtOpenGLWidgets
    - PySide6.QtPdf
    - PySide6.QtPrintSupport
    - PySide6.QtQml
    - PySide6.QtQuick
    - PySide6.QtQuickControls2
    - PySide6.QtQuickWidgets
    - PySide6.QtSql
    - PySide6.QtSvg
    - PySide6.QtSvgWidgets
    - PySide6.QtTest
    - PySide6.QtUiTools
    - PySide6.QtWebChannel
    - PySide6.QtWebEngineCore
    - PySide6.QtWebEngineQuick
    - PySide6.QtWebEngineWidgets
    - PySide6.QtWebSockets
    - PySide6.QtWidgets
    - PySide6.QtXml
  commands:
    - shiboken6 --help
    - pyside6-rcc -help
    - pyside6-uic -help
    - test -f ${PREFIX}/lib/qt6/plugins/designer/libPySidePlugin${SHLIB_EXT}  # [unix]

about:
  home: https://wiki.qt.io/PySide2
  license: LGPL-3.0-only
  license_file: LICENSES/LGPL-3.0-only.txt
  summary: Python bindings for Qt

extra:
  recipe-maintainers:
    - jan-janssen
    - jschueller
