travis:
  secure:
    BINSTAR_TOKEN: reI7h7hl28VJZy88J5fh8lQYh6dv2IJavEfOvih2XbYiA1YXPNSpZKVXqinqgobGuMXOM/r+hO+pOqbGilZpTuiHmesslv8ZPcZszl8ls5b4dc1HEGYefzfG/914v17T0THlMVmSgntGxdDkHMUUeG2BO0wbzj2gntvTl61EnxfXgTbIwgOIHJTTD4AnLuI8mxaUBBShWcMqX2E9ASbSV0LdtKbV7/0X13LClBIHG1PAdE2cPEUsl4d463gcW1qqTURmUX+ICjjlwz353CZWrs2tcewhpAcwBK5/r6tw1GRXxU2y5W0nTC6OfS+uB8tyN9lFnVy/GZLorCftrRFuKHIsjPIpibyvvqD4T6I4MaaREow8VKYP3X1W4DnL/jWFc2oFook7V5L52S+hbr9J+8dJnnAitAZbluCDg3T75UcvK9sXoY88bxaH5XjoYjnH8pIo2mN1H7WzosbOOaK9FbtZwwa/BhT570JemFIhDVFkVhLLo+QVqcleR5+drTq3YSWelj8l4tc9gEsiw1xGKbBFapTkHhLO5JqzOU8MAEdpoNqKTpfGRsFtCAz9nXXy3iZ+X4BbXsKSLPda8EsMmIRox7NczHBNq3v/qKX38kITT9k/EY5SO0UWf7hGGuKJ0z6Ri/h+TiqLZJKQ8Iieb8h/4MVKYaXORAKdgdJws/Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
